### PR TITLE
feat(frontend): created a pipeline to generate pdfs

### PR DESCRIPTION
**Pull request by kouamschekina**
Created a pipeline to convert all `.md` files to `.pdf`

### CODE REVIEW

**Comment by kouamschekina** [comment]
Hello sir @stephane-segning 
When i don't do a `yarn add typedoc` , the pipeline is failing saying the command is not found

**Review by ValantineSuh — APPROVED** [review]
Good!

**Review by Bansikah — APPROVED** [review]

**Review by stephane-segning — APPROVED** [review]
It'll be nice to document how to download the PDFs

**Comment by kouamschekina** [comment]
Done sir @stephane-segning

**Review by ValantineSuh — APPROVED** [review]

**Pull request merged**
