### PR TITLE
style(code): setup commit convention

### PR DESCRIPTION
**Pull request by stephane-segning**

### CODE REVIEW

**Comment by stephane-segning** [comment]
Based on https://www.freecodecamp.org/news/how-to-use-commitlint-to-write-good-commit-messages/

**Review by ValantineSuh — APPROVED** [review]
Good!

**Review by NkwaTambe — APPROVED** [review]
Good job sir

**Review by Bansikah — APPROVED** [review]
Great!

**Review by nancymuyeh — APPROVED** [review]

**Pull request merged**
