### PR TITLE
chore: copied data from electron

### PR DESCRIPTION
**Pull request by stephane-segning**

### CODE REVIEW

**Review by ValantineSuh — APPROVED** [review]
Great Job!

**Review by Koufan-De-King — APPROVED** [review]
Looks great!

**Review by Koufan-De-King — CHANGES_REQUESTED** [review]
Consider the failing check sir.

**Review by ValantineSuh — COMMENTED** [review]
Please Sir, kindly verify the error, causing the checks to fail.

**Review by Koufan-De-King — APPROVED** [review]

**Pull request merged**
